Remove license stanza from all casks (#30)
* Remove license stanza from all casks

Stanza was deprecated in https://github.com/Homebrew/homebrew-cask/issues/17437

* Fix EOS.undent issues

E.g.:
```
$ brew cask info 7zx
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/alehouse/homebrew-unofficial/Casks/7zx.rb:19:in `block in load'
```